events {
    worker_connections 1024;
}

http {
    # This correctly identifies your 10 Docker containers
    upstream backend_cluster {
        server ems-be:1337;
    }

    server {
        listen 80;

        # This is where the domain name goes
        server_name ems-be-dev.dipanshushukla.com;

        location / {
            proxy_pass http://backend_cluster;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # Helps with Spring Boot redirect issues
            proxy_redirect off;
        }
    }
}
